### ISSUE TITLE
背包同时存在多根红石末地烛，副手使用，背包内所有末地烛同时消耗耐久

### ISSUE THREAD

**Issue by suizhuchen** [CSneko/More_end_rod#3]
如题
![image](https://github.com/CSneko/More_end_rod/assets/102964369/c93cd4c7-7efb-4e05-bf7a-b0b4ddb907c7)
而且耐久消耗的还不一样
---
minecraft 1.20.4
fabric 0.15.7
fabric api 0.96.3
moreEndRod 0.0.8
toNekoMod 0.28
ctLibMod 0.0.15
Geckolib 4.4.2
无其他mod，特地新下的端
jdk Zulu 21
Win11 23H2
---

非常好mod

**Comment by suizhuchen** [comment]
因为我没系统学过java，代码我没完全理解，
不过看已关闭的issue，似乎这是一个多根插入的特性？

**Comment by dyhags** [comment]
是的，群里说了喵~没改的就叫特性喵~

**Comment by dyhags** [comment]
是的，群里面说了喵~~~没改的就叫特性~~喵~

**Comment by dyhags** [comment]
是的，群里面说了喵~没改的就叫特性喵~

**Comment by dyhags** [comment]
是的，群里面说了喵~ ~没改的就叫特性喵~

**Comment by suizhuchen** [comment]
明白了，是我🐟不可🐔了
