### ISSUE TITLE
添加冒爱心效果（

### ISSUE THREAD

**Issue by homewool** [CSneko/More_end_rod#4]
不太会github，不会玩pr，也不太了解mcMod开发，总之加了一行冒爱心的代码（
在Orgasm.java中第48行添加：
`world.addParticle(ParticleTypes.HEART,player.getX() + random.nextFloat(2) - 1,player.getY() + random.nextFloat(1) + 2, player.getZ() + random.nextFloat(2) - 1,0,2,0);`
然后头顶就能冒爱心了（

**Comment by CSneko** [comment]
OK，已经加上
